---
- name: Provision workshop
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Run terraform
    terraform:
      project_path: "{{playbook_dir}}"
      force_init: yes
      state: "{{state}}"
